/* Application.c generated by valac 0.48.25, the Vala compiler
 * generated from Application.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>

#define VS_CODE_TYPE_APPLICATION (vs_code_application_get_type ())
#define VS_CODE_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_TYPE_APPLICATION, VSCodeApplication))
#define VS_CODE_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_TYPE_APPLICATION, VSCodeApplicationClass))
#define VS_CODE_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_TYPE_APPLICATION))
#define VS_CODE_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_TYPE_APPLICATION))
#define VS_CODE_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_TYPE_APPLICATION, VSCodeApplicationClass))

typedef struct _VSCodeApplication VSCodeApplication;
typedef struct _VSCodeApplicationClass VSCodeApplicationClass;
typedef struct _VSCodeApplicationPrivate VSCodeApplicationPrivate;

#define VS_CODE_TYPE_WINDOW (vs_code_window_get_type ())
#define VS_CODE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_TYPE_WINDOW, VSCodeWindow))
#define VS_CODE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_TYPE_WINDOW, VSCodeWindowClass))
#define VS_CODE_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_TYPE_WINDOW))
#define VS_CODE_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_TYPE_WINDOW))
#define VS_CODE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_TYPE_WINDOW, VSCodeWindowClass))

typedef struct _VSCodeWindow VSCodeWindow;
typedef struct _VSCodeWindowClass VSCodeWindowClass;
enum  {
	VS_CODE_APPLICATION_0_PROPERTY,
	VS_CODE_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* vs_code_application_properties[VS_CODE_APPLICATION_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _VSCodeApplication {
	GtkApplication parent_instance;
	VSCodeApplicationPrivate * priv;
	GList* windows;
};

struct _VSCodeApplicationClass {
	GtkApplicationClass parent_class;
};

static gpointer vs_code_application_parent_class = NULL;

GType vs_code_application_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeApplication, g_object_unref)
GType vs_code_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeWindow, g_object_unref)
static void _g_object_unref0_ (gpointer var);
static inline void _g_list_free__g_object_unref0_ (GList* self);
void vs_code_application_new_window (VSCodeApplication* self);
VSCodeWindow* vs_code_window_new (VSCodeApplication* vscode_app);
VSCodeWindow* vs_code_window_construct (GType object_type,
                                        VSCodeApplication* vscode_app);
static void vs_code_application_real_window_added (GtkApplication* base,
                                            GtkWindow* window);
static void vs_code_application_real_window_removed (GtkApplication* base,
                                              GtkWindow* window);
static VSCodeWindow* vs_code_application_add_new_window (VSCodeApplication* self);
static void vs_code_application_real_activate (GApplication* base);
VSCodeApplication* vs_code_application_new (void);
VSCodeApplication* vs_code_application_construct (GType object_type);
static GObject * vs_code_application_constructor (GType type,
                                           guint n_construct_properties,
                                           GObjectConstructParam * construct_properties);
#define CONSTANTS_PROJECT_NAME "com.github.basson_xvi.vscode"
static void vs_code_application_finalize (GObject * obj);
static GType vs_code_application_get_type_once (void);

static void
_g_object_unref0_ (gpointer var)
{
#line 3 "../src/Application.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 81 "Application.c"
}

static inline void
_g_list_free__g_object_unref0_ (GList* self)
{
#line 3 "../src/Application.vala"
	g_list_free_full (self, (GDestroyNotify) _g_object_unref0_);
#line 89 "Application.c"
}

void
vs_code_application_new_window (VSCodeApplication* self)
{
	VSCodeWindow* _tmp0_;
	VSCodeWindow* _tmp1_;
#line 17 "../src/Application.vala"
	g_return_if_fail (self != NULL);
#line 18 "../src/Application.vala"
	_tmp0_ = vs_code_window_new (self);
#line 18 "../src/Application.vala"
	g_object_ref_sink (_tmp0_);
#line 18 "../src/Application.vala"
	_tmp1_ = _tmp0_;
#line 18 "../src/Application.vala"
	gtk_window_present ((GtkWindow*) _tmp1_);
#line 18 "../src/Application.vala"
	_g_object_unref0 (_tmp1_);
#line 109 "Application.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 22 "../src/Application.vala"
	return self ? g_object_ref (self) : NULL;
#line 117 "Application.c"
}

static void
vs_code_application_real_window_added (GtkApplication* base,
                                       GtkWindow* window)
{
	VSCodeApplication * self;
	VSCodeWindow* _tmp0_;
#line 21 "../src/Application.vala"
	self = (VSCodeApplication*) base;
#line 21 "../src/Application.vala"
	g_return_if_fail (window != NULL);
#line 22 "../src/Application.vala"
	_tmp0_ = _g_object_ref0 (VS_CODE_IS_WINDOW (window) ? ((VSCodeWindow*) window) : NULL);
#line 22 "../src/Application.vala"
	self->windows = g_list_append (self->windows, _tmp0_);
#line 23 "../src/Application.vala"
	GTK_APPLICATION_CLASS (vs_code_application_parent_class)->window_added (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication), window);
#line 136 "Application.c"
}

static GList*
vala_g_list_remove_full (GList* self,
                         gconstpointer data,
                         GFreeFunc func)
{
	GList* l = NULL;
	GList* result = NULL;
#line 4911 "glib-2.0.vapi"
	l = self;
#line 4912 "glib-2.0.vapi"
	while (TRUE) {
#line 150 "Application.c"
		GList* _tmp0_;
		GList* _tmp1_;
		gconstpointer _tmp2_;
#line 4912 "glib-2.0.vapi"
		_tmp0_ = l;
#line 4912 "glib-2.0.vapi"
		if (!(_tmp0_ != NULL)) {
#line 4912 "glib-2.0.vapi"
			break;
#line 160 "Application.c"
		}
#line 4913 "glib-2.0.vapi"
		_tmp1_ = l;
#line 4913 "glib-2.0.vapi"
		_tmp2_ = ((GList*) _tmp1_)->data;
#line 4913 "glib-2.0.vapi"
		if (_tmp2_ != data) {
#line 168 "Application.c"
			GList* _tmp3_;
			GList* _tmp4_;
#line 4914 "glib-2.0.vapi"
			_tmp3_ = l;
#line 4914 "glib-2.0.vapi"
			_tmp4_ = ((GList*) _tmp3_)->next;
#line 4914 "glib-2.0.vapi"
			l = _tmp4_;
#line 177 "Application.c"
		} else {
			GList* _tmp5_;
			gconstpointer _tmp6_;
			GList* _tmp7_;
#line 4916 "glib-2.0.vapi"
			_tmp5_ = l;
#line 4916 "glib-2.0.vapi"
			_tmp6_ = ((GList*) _tmp5_)->data;
#line 4916 "glib-2.0.vapi"
			func (_tmp6_);
#line 4917 "glib-2.0.vapi"
			_tmp7_ = l;
#line 4917 "glib-2.0.vapi"
			self = g_list_delete_link (self, (GList*) _tmp7_);
#line 4918 "glib-2.0.vapi"
			break;
#line 194 "Application.c"
		}
	}
#line 4921 "glib-2.0.vapi"
	result = self;
#line 4921 "glib-2.0.vapi"
	return result;
#line 201 "Application.c"
}

static void
vs_code_application_real_window_removed (GtkApplication* base,
                                         GtkWindow* window)
{
	VSCodeApplication * self;
#line 27 "../src/Application.vala"
	self = (VSCodeApplication*) base;
#line 27 "../src/Application.vala"
	g_return_if_fail (window != NULL);
#line 28 "../src/Application.vala"
	self->windows = vala_g_list_remove_full (self->windows, VS_CODE_IS_WINDOW (window) ? ((VSCodeWindow*) window) : NULL, _g_object_unref0_);
#line 29 "../src/Application.vala"
	GTK_APPLICATION_CLASS (vs_code_application_parent_class)->window_removed (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication), window);
#line 217 "Application.c"
}

static VSCodeWindow*
vs_code_application_add_new_window (VSCodeApplication* self)
{
	VSCodeWindow* window = NULL;
	VSCodeWindow* _tmp0_;
	VSCodeWindow* result = NULL;
#line 32 "../src/Application.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 33 "../src/Application.vala"
	_tmp0_ = vs_code_window_new (self);
#line 33 "../src/Application.vala"
	g_object_ref_sink (_tmp0_);
#line 33 "../src/Application.vala"
	window = _tmp0_;
#line 34 "../src/Application.vala"
	gtk_application_add_window ((GtkApplication*) self, (GtkWindow*) window);
#line 36 "../src/Application.vala"
	result = window;
#line 36 "../src/Application.vala"
	return result;
#line 240 "Application.c"
}

static void
vs_code_application_real_activate (GApplication* base)
{
	VSCodeApplication * self;
	VSCodeWindow* _tmp0_;
	VSCodeWindow* _tmp1_;
#line 39 "../src/Application.vala"
	self = (VSCodeApplication*) base;
#line 40 "../src/Application.vala"
	_tmp0_ = vs_code_application_add_new_window (self);
#line 40 "../src/Application.vala"
	_tmp1_ = _tmp0_;
#line 40 "../src/Application.vala"
	_g_object_unref0 (_tmp1_);
#line 257 "Application.c"
}

VSCodeApplication*
vs_code_application_construct (GType object_type)
{
	VSCodeApplication * self = NULL;
#line 2 "../src/Application.vala"
	self = (VSCodeApplication*) g_object_new (object_type, NULL);
#line 2 "../src/Application.vala"
	return self;
#line 268 "Application.c"
}

VSCodeApplication*
vs_code_application_new (void)
{
#line 2 "../src/Application.vala"
	return vs_code_application_construct (VS_CODE_TYPE_APPLICATION);
#line 276 "Application.c"
}

static GObject *
vs_code_application_constructor (GType type,
                                 guint n_construct_properties,
                                 GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	VSCodeApplication * self;
	GApplicationFlags _tmp0_;
	GApplicationFlags _tmp1_;
#line 5 "../src/Application.vala"
	parent_class = G_OBJECT_CLASS (vs_code_application_parent_class);
#line 5 "../src/Application.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 5 "../src/Application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VS_CODE_TYPE_APPLICATION, VSCodeApplication);
#line 6 "../src/Application.vala"
	g_application_set_application_id ((GApplication*) self, CONSTANTS_PROJECT_NAME);
#line 7 "../src/Application.vala"
	_tmp0_ = g_application_get_flags ((GApplication*) self);
#line 7 "../src/Application.vala"
	_tmp1_ = _tmp0_;
#line 7 "../src/Application.vala"
	g_application_set_flags ((GApplication*) self, _tmp1_ | G_APPLICATION_HANDLES_OPEN);
#line 14 "../src/Application.vala"
	(self->windows == NULL) ? NULL : (self->windows = (_g_list_free__g_object_unref0_ (self->windows), NULL));
#line 14 "../src/Application.vala"
	self->windows = NULL;
#line 5 "../src/Application.vala"
	return obj;
#line 309 "Application.c"
}

static void
vs_code_application_class_init (VSCodeApplicationClass * klass,
                                gpointer klass_data)
{
#line 2 "../src/Application.vala"
	vs_code_application_parent_class = g_type_class_peek_parent (klass);
#line 2 "../src/Application.vala"
	((GtkApplicationClass *) klass)->window_added = (void (*) (GtkApplication*, GtkWindow*)) vs_code_application_real_window_added;
#line 2 "../src/Application.vala"
	((GtkApplicationClass *) klass)->window_removed = (void (*) (GtkApplication*, GtkWindow*)) vs_code_application_real_window_removed;
#line 2 "../src/Application.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) vs_code_application_real_activate;
#line 2 "../src/Application.vala"
	G_OBJECT_CLASS (klass)->constructor = vs_code_application_constructor;
#line 2 "../src/Application.vala"
	G_OBJECT_CLASS (klass)->finalize = vs_code_application_finalize;
#line 328 "Application.c"
}

static void
vs_code_application_instance_init (VSCodeApplication * self,
                                   gpointer klass)
{
}

static void
vs_code_application_finalize (GObject * obj)
{
	VSCodeApplication * self;
#line 2 "../src/Application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VS_CODE_TYPE_APPLICATION, VSCodeApplication);
#line 3 "../src/Application.vala"
	(self->windows == NULL) ? NULL : (self->windows = (_g_list_free__g_object_unref0_ (self->windows), NULL));
#line 2 "../src/Application.vala"
	G_OBJECT_CLASS (vs_code_application_parent_class)->finalize (obj);
#line 347 "Application.c"
}

static GType
vs_code_application_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (VSCodeApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vs_code_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (VSCodeApplication), 0, (GInstanceInitFunc) vs_code_application_instance_init, NULL };
	GType vs_code_application_type_id;
	vs_code_application_type_id = g_type_register_static (gtk_application_get_type (), "VSCodeApplication", &g_define_type_info, 0);
	return vs_code_application_type_id;
}

GType
vs_code_application_get_type (void)
{
	static volatile gsize vs_code_application_type_id__volatile = 0;
	if (g_once_init_enter (&vs_code_application_type_id__volatile)) {
		GType vs_code_application_type_id;
		vs_code_application_type_id = vs_code_application_get_type_once ();
		g_once_init_leave (&vs_code_application_type_id__volatile, vs_code_application_type_id);
	}
	return vs_code_application_type_id__volatile;
}

