/* config.c generated by valac 0.48.25, the Vala compiler
 * generated from config.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define CONSTANTS_PROJECT_NAME "com.github.basson_xvi.vscode"
#define CONSTANTS_GETTEXT_PACKAGE "com.github.basson_xvi.vscode"
#define CONSTANTS_VERSION "0.0.1"

