/* Main.c generated by valac 0.48.25, the Vala compiler
 * generated from Main.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>

#define VS_CODE_TYPE_APPLICATION (vs_code_application_get_type ())
#define VS_CODE_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_TYPE_APPLICATION, VSCodeApplication))
#define VS_CODE_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_TYPE_APPLICATION, VSCodeApplicationClass))
#define VS_CODE_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_TYPE_APPLICATION))
#define VS_CODE_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_TYPE_APPLICATION))
#define VS_CODE_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_TYPE_APPLICATION, VSCodeApplicationClass))

typedef struct _VSCodeApplication VSCodeApplication;
typedef struct _VSCodeApplicationClass VSCodeApplicationClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define APP_NAME "VSCode PM"
#define TERMINAL_NAME "codepm"
static gint _vala_main (gchar** args,
                 gint args_length1);
GType vs_code_application_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeApplication, g_object_unref)
VSCodeApplication* vs_code_application_new (void);
VSCodeApplication* vs_code_application_construct (GType object_type);

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	VSCodeApplication* application = NULL;
	VSCodeApplication* _tmp0_;
	gint result = 0;
#line 9 "../src/Main.vala"
	g_set_application_name ("VSCode PM");
#line 10 "../src/Main.vala"
	g_set_prgname ("VSCode PM");
#line 12 "../src/Main.vala"
	_tmp0_ = vs_code_application_new ();
#line 12 "../src/Main.vala"
	application = _tmp0_;
#line 14 "../src/Main.vala"
	result = g_application_run ((GApplication*) application, (gint) args_length1, args);
#line 14 "../src/Main.vala"
	_g_object_unref0 (application);
#line 14 "../src/Main.vala"
	return result;
#line 53 "Main.c"
}

int
main (int argc,
      char ** argv)
{
#line 8 "../src/Main.vala"
	return _vala_main (argv, argc);
#line 62 "Main.c"
}

