/* Window.c generated by valac 0.48.25, the Vala compiler
 * generated from Window.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>

#define VS_CODE_TYPE_WINDOW (vs_code_window_get_type ())
#define VS_CODE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_TYPE_WINDOW, VSCodeWindow))
#define VS_CODE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_TYPE_WINDOW, VSCodeWindowClass))
#define VS_CODE_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_TYPE_WINDOW))
#define VS_CODE_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_TYPE_WINDOW))
#define VS_CODE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_TYPE_WINDOW, VSCodeWindowClass))

typedef struct _VSCodeWindow VSCodeWindow;
typedef struct _VSCodeWindowClass VSCodeWindowClass;
typedef struct _VSCodeWindowPrivate VSCodeWindowPrivate;

#define VS_CODE_LAYOUTS_TYPE_MAIN (vs_code_layouts_main_get_type ())
#define VS_CODE_LAYOUTS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_LAYOUTS_TYPE_MAIN, VSCodeLayoutsMain))
#define VS_CODE_LAYOUTS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_LAYOUTS_TYPE_MAIN, VSCodeLayoutsMainClass))
#define VS_CODE_LAYOUTS_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_LAYOUTS_TYPE_MAIN))
#define VS_CODE_LAYOUTS_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_LAYOUTS_TYPE_MAIN))
#define VS_CODE_LAYOUTS_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_LAYOUTS_TYPE_MAIN, VSCodeLayoutsMainClass))

typedef struct _VSCodeLayoutsMain VSCodeLayoutsMain;
typedef struct _VSCodeLayoutsMainClass VSCodeLayoutsMainClass;

#define VS_CODE_LAYOUTS_TYPE_HEADER_BAR (vs_code_layouts_header_bar_get_type ())
#define VS_CODE_LAYOUTS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBar))
#define VS_CODE_LAYOUTS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBarClass))
#define VS_CODE_LAYOUTS_IS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_LAYOUTS_TYPE_HEADER_BAR))
#define VS_CODE_LAYOUTS_IS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_LAYOUTS_TYPE_HEADER_BAR))
#define VS_CODE_LAYOUTS_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBarClass))

typedef struct _VSCodeLayoutsHeaderBar VSCodeLayoutsHeaderBar;
typedef struct _VSCodeLayoutsHeaderBarClass VSCodeLayoutsHeaderBarClass;

#define VS_CODE_TYPE_APPLICATION (vs_code_application_get_type ())
#define VS_CODE_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_TYPE_APPLICATION, VSCodeApplication))
#define VS_CODE_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_TYPE_APPLICATION, VSCodeApplicationClass))
#define VS_CODE_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_TYPE_APPLICATION))
#define VS_CODE_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_TYPE_APPLICATION))
#define VS_CODE_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_TYPE_APPLICATION, VSCodeApplicationClass))

typedef struct _VSCodeApplication VSCodeApplication;
typedef struct _VSCodeApplicationClass VSCodeApplicationClass;
enum  {
	VS_CODE_WINDOW_0_PROPERTY,
	VS_CODE_WINDOW_APP_PROPERTY,
	VS_CODE_WINDOW_ACCEL_GROUP_PROPERTY,
	VS_CODE_WINDOW_NUM_PROPERTIES
};
static GParamSpec* vs_code_window_properties[VS_CODE_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _VSCodeWindow {
	GtkApplicationWindow parent_instance;
	VSCodeWindowPrivate * priv;
	VSCodeLayoutsMain* main;
	VSCodeLayoutsHeaderBar* headerbar;
};

struct _VSCodeWindowClass {
	GtkApplicationWindowClass parent_class;
};

struct _VSCodeWindowPrivate {
	VSCodeApplication* _app;
	GtkAccelGroup* _accel_group;
};

static gint VSCodeWindow_private_offset;
static gpointer vs_code_window_parent_class = NULL;

GType vs_code_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeWindow, g_object_unref)
GType vs_code_layouts_main_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeLayoutsMain, g_object_unref)
GType vs_code_layouts_header_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeLayoutsHeaderBar, g_object_unref)
GType vs_code_application_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeApplication, g_object_unref)
VSCodeWindow* vs_code_window_new (VSCodeApplication* vscode_app);
VSCodeWindow* vs_code_window_construct (GType object_type,
                                        VSCodeApplication* vscode_app);
#define CONSTANTS_PROJECT_NAME "com.github.basson_xvi.vscode"
VSCodeWindow* vs_code_window_get_instance (VSCodeWindow* self);
static void vs_code_window_build_ui (VSCodeWindow* self);
gboolean vs_code_window_before_destroy (VSCodeWindow* self);
static gboolean _vs_code_window_before_destroy_gtk_widget_delete_event (GtkWidget* _sender,
                                                                 GdkEventAny* event,
                                                                 gpointer self);
static void vs_code_window_update_status (VSCodeWindow* self);
VSCodeApplication* vs_code_window_get_app (VSCodeWindow* self);
void vs_code_window_show_app (VSCodeWindow* self);
static void vs_code_window_set_app (VSCodeWindow* self,
                             VSCodeApplication* value);
GtkAccelGroup* vs_code_window_get_accel_group (VSCodeWindow* self);
static void vs_code_window_set_accel_group (VSCodeWindow* self,
                                     GtkAccelGroup* value);
static GObject * vs_code_window_constructor (GType type,
                                      guint n_construct_properties,
                                      GObjectConstructParam * construct_properties);
VSCodeLayoutsMain* vs_code_layouts_main_new (VSCodeWindow* main_window);
VSCodeLayoutsMain* vs_code_layouts_main_construct (GType object_type,
                                                   VSCodeWindow* main_window);
VSCodeLayoutsHeaderBar* vs_code_layouts_header_bar_new (VSCodeWindow* main_window);
VSCodeLayoutsHeaderBar* vs_code_layouts_header_bar_construct (GType object_type,
                                                              VSCodeWindow* main_window);
static void vs_code_window_finalize (GObject * obj);
static GType vs_code_window_get_type_once (void);
static void _vala_vs_code_window_get_property (GObject * object,
                                        guint property_id,
                                        GValue * value,
                                        GParamSpec * pspec);
static void _vala_vs_code_window_set_property (GObject * object,
                                        guint property_id,
                                        const GValue * value,
                                        GParamSpec * pspec);

static inline gpointer
vs_code_window_get_instance_private (VSCodeWindow* self)
{
	return G_STRUCT_MEMBER_P (self, VSCodeWindow_private_offset);
}

VSCodeWindow*
vs_code_window_construct (GType object_type,
                          VSCodeApplication* vscode_app)
{
	VSCodeWindow * self = NULL;
#line 11 "../src/Window.vala"
	g_return_val_if_fail (vscode_app != NULL, NULL);
#line 12 "../src/Window.vala"
	self = (VSCodeWindow*) g_object_new (object_type, "application", vscode_app, "app", vscode_app, "icon-name", CONSTANTS_PROJECT_NAME, NULL);
#line 11 "../src/Window.vala"
	return self;
#line 143 "Window.c"
}

VSCodeWindow*
vs_code_window_new (VSCodeApplication* vscode_app)
{
#line 11 "../src/Window.vala"
	return vs_code_window_construct (VS_CODE_TYPE_WINDOW, vscode_app);
#line 151 "Window.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 32 "../src/Window.vala"
	return self ? g_object_ref (self) : NULL;
#line 159 "Window.c"
}

VSCodeWindow*
vs_code_window_get_instance (VSCodeWindow* self)
{
	VSCodeWindow* _tmp0_;
	VSCodeWindow* result = NULL;
#line 31 "../src/Window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 32 "../src/Window.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 32 "../src/Window.vala"
	result = _tmp0_;
#line 32 "../src/Window.vala"
	return result;
#line 175 "Window.c"
}

static gboolean
_vs_code_window_before_destroy_gtk_widget_delete_event (GtkWidget* _sender,
                                                        GdkEventAny* event,
                                                        gpointer self)
{
	gboolean result;
	result = vs_code_window_before_destroy ((VSCodeWindow*) self);
#line 38 "../src/Window.vala"
	return result;
#line 187 "Window.c"
}

static void
vs_code_window_build_ui (VSCodeWindow* self)
{
	VSCodeLayoutsHeaderBar* _tmp0_;
	VSCodeLayoutsMain* _tmp1_;
#line 35 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 38 "../src/Window.vala"
	g_signal_connect_object ((GtkWidget*) self, "delete-event", (GCallback) _vs_code_window_before_destroy_gtk_widget_delete_event, self, 0);
#line 39 "../src/Window.vala"
	_tmp0_ = self->headerbar;
#line 39 "../src/Window.vala"
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) _tmp0_);
#line 40 "../src/Window.vala"
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 0);
#line 41 "../src/Window.vala"
	_tmp1_ = self->main;
#line 41 "../src/Window.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp1_);
#line 209 "Window.c"
}

gboolean
vs_code_window_before_destroy (VSCodeWindow* self)
{
	VSCodeApplication* _tmp0_;
	GtkWindow* _tmp1_;
	gboolean result = FALSE;
#line 44 "../src/Window.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 45 "../src/Window.vala"
	vs_code_window_update_status (self);
#line 46 "../src/Window.vala"
	_tmp0_ = self->priv->_app;
#line 46 "../src/Window.vala"
	_tmp1_ = gtk_application_get_active_window ((GtkApplication*) _tmp0_);
#line 46 "../src/Window.vala"
	gtk_widget_destroy ((GtkWidget*) _tmp1_);
#line 47 "../src/Window.vala"
	result = TRUE;
#line 47 "../src/Window.vala"
	return result;
#line 232 "Window.c"
}

static void
vs_code_window_update_status (VSCodeWindow* self)
{
#line 50 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 240 "Window.c"
}

void
vs_code_window_show_app (VSCodeWindow* self)
{
#line 54 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 55 "../src/Window.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 56 "../src/Window.vala"
	gtk_widget_show ((GtkWidget*) self);
#line 57 "../src/Window.vala"
	gtk_window_present ((GtkWindow*) self);
#line 254 "Window.c"
}

VSCodeApplication*
vs_code_window_get_app (VSCodeWindow* self)
{
	VSCodeApplication* result;
	VSCodeApplication* _tmp0_;
#line 3 "../src/Window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 3 "../src/Window.vala"
	_tmp0_ = self->priv->_app;
#line 3 "../src/Window.vala"
	result = _tmp0_;
#line 3 "../src/Window.vala"
	return result;
#line 270 "Window.c"
}

static void
vs_code_window_set_app (VSCodeWindow* self,
                        VSCodeApplication* value)
{
	VSCodeApplication* old_value;
#line 3 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 3 "../src/Window.vala"
	old_value = vs_code_window_get_app (self);
#line 3 "../src/Window.vala"
	if (old_value != value) {
#line 3 "../src/Window.vala"
		self->priv->_app = value;
#line 3 "../src/Window.vala"
		g_object_notify_by_pspec ((GObject *) self, vs_code_window_properties[VS_CODE_WINDOW_APP_PROPERTY]);
#line 288 "Window.c"
	}
}

GtkAccelGroup*
vs_code_window_get_accel_group (VSCodeWindow* self)
{
	GtkAccelGroup* result;
	GtkAccelGroup* _tmp0_;
#line 9 "../src/Window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 9 "../src/Window.vala"
	_tmp0_ = self->priv->_accel_group;
#line 9 "../src/Window.vala"
	result = _tmp0_;
#line 9 "../src/Window.vala"
	return result;
#line 305 "Window.c"
}

static void
vs_code_window_set_accel_group (VSCodeWindow* self,
                                GtkAccelGroup* value)
{
	GtkAccelGroup* old_value;
#line 9 "../src/Window.vala"
	g_return_if_fail (self != NULL);
#line 9 "../src/Window.vala"
	old_value = vs_code_window_get_accel_group (self);
#line 9 "../src/Window.vala"
	if (old_value != value) {
#line 319 "Window.c"
		GtkAccelGroup* _tmp0_;
#line 9 "../src/Window.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 9 "../src/Window.vala"
		_g_object_unref0 (self->priv->_accel_group);
#line 9 "../src/Window.vala"
		self->priv->_accel_group = _tmp0_;
#line 9 "../src/Window.vala"
		g_object_notify_by_pspec ((GObject *) self, vs_code_window_properties[VS_CODE_WINDOW_ACCEL_GROUP_PROPERTY]);
#line 329 "Window.c"
	}
}

static GObject *
vs_code_window_constructor (GType type,
                            guint n_construct_properties,
                            GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	VSCodeWindow * self;
	GtkAccelGroup* _tmp0_;
	GtkAccelGroup* _tmp1_;
	GtkAccelGroup* _tmp2_;
	VSCodeLayoutsMain* _tmp3_;
	VSCodeLayoutsHeaderBar* _tmp4_;
#line 19 "../src/Window.vala"
	parent_class = G_OBJECT_CLASS (vs_code_window_parent_class);
#line 19 "../src/Window.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 19 "../src/Window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VS_CODE_TYPE_WINDOW, VSCodeWindow);
#line 20 "../src/Window.vala"
	_tmp0_ = gtk_accel_group_new ();
#line 20 "../src/Window.vala"
	_tmp1_ = _tmp0_;
#line 20 "../src/Window.vala"
	vs_code_window_set_accel_group (self, _tmp1_);
#line 20 "../src/Window.vala"
	_g_object_unref0 (_tmp1_);
#line 21 "../src/Window.vala"
	_tmp2_ = self->priv->_accel_group;
#line 21 "../src/Window.vala"
	gtk_window_add_accel_group ((GtkWindow*) self, _tmp2_);
#line 23 "../src/Window.vala"
	_tmp3_ = vs_code_layouts_main_new (self);
#line 23 "../src/Window.vala"
	g_object_ref_sink (_tmp3_);
#line 23 "../src/Window.vala"
	_g_object_unref0 (self->main);
#line 23 "../src/Window.vala"
	self->main = _tmp3_;
#line 24 "../src/Window.vala"
	_tmp4_ = vs_code_layouts_header_bar_new (self);
#line 24 "../src/Window.vala"
	g_object_ref_sink (_tmp4_);
#line 24 "../src/Window.vala"
	_g_object_unref0 (self->headerbar);
#line 24 "../src/Window.vala"
	self->headerbar = _tmp4_;
#line 26 "../src/Window.vala"
	vs_code_window_build_ui (self);
#line 28 "../src/Window.vala"
	vs_code_window_show_app (self);
#line 19 "../src/Window.vala"
	return obj;
#line 386 "Window.c"
}

static void
vs_code_window_class_init (VSCodeWindowClass * klass,
                           gpointer klass_data)
{
#line 2 "../src/Window.vala"
	vs_code_window_parent_class = g_type_class_peek_parent (klass);
#line 2 "../src/Window.vala"
	g_type_class_adjust_private_offset (klass, &VSCodeWindow_private_offset);
#line 2 "../src/Window.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_vs_code_window_get_property;
#line 2 "../src/Window.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_vs_code_window_set_property;
#line 2 "../src/Window.vala"
	G_OBJECT_CLASS (klass)->constructor = vs_code_window_constructor;
#line 2 "../src/Window.vala"
	G_OBJECT_CLASS (klass)->finalize = vs_code_window_finalize;
#line 2 "../src/Window.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), VS_CODE_WINDOW_APP_PROPERTY, vs_code_window_properties[VS_CODE_WINDOW_APP_PROPERTY] = g_param_spec_object ("app", "app", "app", VS_CODE_TYPE_APPLICATION, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 2 "../src/Window.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), VS_CODE_WINDOW_ACCEL_GROUP_PROPERTY, vs_code_window_properties[VS_CODE_WINDOW_ACCEL_GROUP_PROPERTY] = g_param_spec_object ("accel-group", "accel-group", "accel-group", gtk_accel_group_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 409 "Window.c"
}

static void
vs_code_window_instance_init (VSCodeWindow * self,
                              gpointer klass)
{
#line 2 "../src/Window.vala"
	self->priv = vs_code_window_get_instance_private (self);
#line 418 "Window.c"
}

static void
vs_code_window_finalize (GObject * obj)
{
	VSCodeWindow * self;
#line 2 "../src/Window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VS_CODE_TYPE_WINDOW, VSCodeWindow);
#line 5 "../src/Window.vala"
	_g_object_unref0 (self->main);
#line 6 "../src/Window.vala"
	_g_object_unref0 (self->headerbar);
#line 9 "../src/Window.vala"
	_g_object_unref0 (self->priv->_accel_group);
#line 2 "../src/Window.vala"
	G_OBJECT_CLASS (vs_code_window_parent_class)->finalize (obj);
#line 435 "Window.c"
}

static GType
vs_code_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (VSCodeWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vs_code_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (VSCodeWindow), 0, (GInstanceInitFunc) vs_code_window_instance_init, NULL };
	GType vs_code_window_type_id;
	vs_code_window_type_id = g_type_register_static (gtk_application_window_get_type (), "VSCodeWindow", &g_define_type_info, 0);
	VSCodeWindow_private_offset = g_type_add_instance_private (vs_code_window_type_id, sizeof (VSCodeWindowPrivate));
	return vs_code_window_type_id;
}

GType
vs_code_window_get_type (void)
{
	static volatile gsize vs_code_window_type_id__volatile = 0;
	if (g_once_init_enter (&vs_code_window_type_id__volatile)) {
		GType vs_code_window_type_id;
		vs_code_window_type_id = vs_code_window_get_type_once ();
		g_once_init_leave (&vs_code_window_type_id__volatile, vs_code_window_type_id);
	}
	return vs_code_window_type_id__volatile;
}

static void
_vala_vs_code_window_get_property (GObject * object,
                                   guint property_id,
                                   GValue * value,
                                   GParamSpec * pspec)
{
	VSCodeWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VS_CODE_TYPE_WINDOW, VSCodeWindow);
#line 2 "../src/Window.vala"
	switch (property_id) {
#line 2 "../src/Window.vala"
		case VS_CODE_WINDOW_APP_PROPERTY:
#line 2 "../src/Window.vala"
		g_value_set_object (value, vs_code_window_get_app (self));
#line 2 "../src/Window.vala"
		break;
#line 2 "../src/Window.vala"
		case VS_CODE_WINDOW_ACCEL_GROUP_PROPERTY:
#line 2 "../src/Window.vala"
		g_value_set_object (value, vs_code_window_get_accel_group (self));
#line 2 "../src/Window.vala"
		break;
#line 482 "Window.c"
		default:
#line 2 "../src/Window.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Window.vala"
		break;
#line 488 "Window.c"
	}
}

static void
_vala_vs_code_window_set_property (GObject * object,
                                   guint property_id,
                                   const GValue * value,
                                   GParamSpec * pspec)
{
	VSCodeWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VS_CODE_TYPE_WINDOW, VSCodeWindow);
#line 2 "../src/Window.vala"
	switch (property_id) {
#line 2 "../src/Window.vala"
		case VS_CODE_WINDOW_APP_PROPERTY:
#line 2 "../src/Window.vala"
		vs_code_window_set_app (self, g_value_get_object (value));
#line 2 "../src/Window.vala"
		break;
#line 2 "../src/Window.vala"
		case VS_CODE_WINDOW_ACCEL_GROUP_PROPERTY:
#line 2 "../src/Window.vala"
		vs_code_window_set_accel_group (self, g_value_get_object (value));
#line 2 "../src/Window.vala"
		break;
#line 514 "Window.c"
		default:
#line 2 "../src/Window.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Window.vala"
		break;
#line 520 "Window.c"
	}
}

