/* HeaderBar.c generated by valac 0.48.25, the Vala compiler
 * generated from HeaderBar.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#define VS_CODE_LAYOUTS_TYPE_HEADER_BAR (vs_code_layouts_header_bar_get_type ())
#define VS_CODE_LAYOUTS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBar))
#define VS_CODE_LAYOUTS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBarClass))
#define VS_CODE_LAYOUTS_IS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_LAYOUTS_TYPE_HEADER_BAR))
#define VS_CODE_LAYOUTS_IS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_LAYOUTS_TYPE_HEADER_BAR))
#define VS_CODE_LAYOUTS_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBarClass))

typedef struct _VSCodeLayoutsHeaderBar VSCodeLayoutsHeaderBar;
typedef struct _VSCodeLayoutsHeaderBarClass VSCodeLayoutsHeaderBarClass;
typedef struct _VSCodeLayoutsHeaderBarPrivate VSCodeLayoutsHeaderBarPrivate;

#define VS_CODE_TYPE_WINDOW (vs_code_window_get_type ())
#define VS_CODE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_TYPE_WINDOW, VSCodeWindow))
#define VS_CODE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_TYPE_WINDOW, VSCodeWindowClass))
#define VS_CODE_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_TYPE_WINDOW))
#define VS_CODE_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_TYPE_WINDOW))
#define VS_CODE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_TYPE_WINDOW, VSCodeWindowClass))

typedef struct _VSCodeWindow VSCodeWindow;
typedef struct _VSCodeWindowClass VSCodeWindowClass;
enum  {
	VS_CODE_LAYOUTS_HEADER_BAR_0_PROPERTY,
	VS_CODE_LAYOUTS_HEADER_BAR_WINDOW_PROPERTY,
	VS_CODE_LAYOUTS_HEADER_BAR_LOGGED_OUT_PROPERTY,
	VS_CODE_LAYOUTS_HEADER_BAR_NUM_PROPERTIES
};
static GParamSpec* vs_code_layouts_header_bar_properties[VS_CODE_LAYOUTS_HEADER_BAR_NUM_PROPERTIES];

struct _VSCodeLayoutsHeaderBar {
	GtkHeaderBar parent_instance;
	VSCodeLayoutsHeaderBarPrivate * priv;
};

struct _VSCodeLayoutsHeaderBarClass {
	GtkHeaderBarClass parent_class;
};

struct _VSCodeLayoutsHeaderBarPrivate {
	VSCodeWindow* _window;
	gboolean _logged_out;
};

static gint VSCodeLayoutsHeaderBar_private_offset;
static gpointer vs_code_layouts_header_bar_parent_class = NULL;

GType vs_code_layouts_header_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeLayoutsHeaderBar, g_object_unref)
GType vs_code_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeWindow, g_object_unref)
VSCodeLayoutsHeaderBar* vs_code_layouts_header_bar_new (VSCodeWindow* main_window);
VSCodeLayoutsHeaderBar* vs_code_layouts_header_bar_construct (GType object_type,
                                                              VSCodeWindow* main_window);
#define APP_NAME "VSCode PM"
static void vs_code_layouts_header_bar_build_ui (VSCodeLayoutsHeaderBar* self);
VSCodeWindow* vs_code_layouts_header_bar_get_window (VSCodeLayoutsHeaderBar* self);
static void vs_code_layouts_header_bar_set_window (VSCodeLayoutsHeaderBar* self,
                                            VSCodeWindow* value);
gboolean vs_code_layouts_header_bar_get_logged_out (VSCodeLayoutsHeaderBar* self);
void vs_code_layouts_header_bar_set_logged_out (VSCodeLayoutsHeaderBar* self,
                                                gboolean value);
static void vs_code_layouts_header_bar_finalize (GObject * obj);
static GType vs_code_layouts_header_bar_get_type_once (void);
static void _vala_vs_code_layouts_header_bar_get_property (GObject * object,
                                                    guint property_id,
                                                    GValue * value,
                                                    GParamSpec * pspec);
static void _vala_vs_code_layouts_header_bar_set_property (GObject * object,
                                                    guint property_id,
                                                    const GValue * value,
                                                    GParamSpec * pspec);

static inline gpointer
vs_code_layouts_header_bar_get_instance_private (VSCodeLayoutsHeaderBar* self)
{
	return G_STRUCT_MEMBER_P (self, VSCodeLayoutsHeaderBar_private_offset);
}

VSCodeLayoutsHeaderBar*
vs_code_layouts_header_bar_construct (GType object_type,
                                      VSCodeWindow* main_window)
{
	VSCodeLayoutsHeaderBar * self = NULL;
#line 14 "../src/Layouts/HeaderBar.vala"
	g_return_val_if_fail (main_window != NULL, NULL);
#line 15 "../src/Layouts/HeaderBar.vala"
	self = (VSCodeLayoutsHeaderBar*) g_object_new (object_type, "window", main_window, "logged-out", TRUE, NULL);
#line 20 "../src/Layouts/HeaderBar.vala"
	gtk_header_bar_set_title ((GtkHeaderBar*) self, APP_NAME);
#line 21 "../src/Layouts/HeaderBar.vala"
	gtk_header_bar_set_show_close_button ((GtkHeaderBar*) self, TRUE);
#line 23 "../src/Layouts/HeaderBar.vala"
	vs_code_layouts_header_bar_build_ui (self);
#line 14 "../src/Layouts/HeaderBar.vala"
	return self;
#line 105 "HeaderBar.c"
}

VSCodeLayoutsHeaderBar*
vs_code_layouts_header_bar_new (VSCodeWindow* main_window)
{
#line 14 "../src/Layouts/HeaderBar.vala"
	return vs_code_layouts_header_bar_construct (VS_CODE_LAYOUTS_TYPE_HEADER_BAR, main_window);
#line 113 "HeaderBar.c"
}

static void
vs_code_layouts_header_bar_build_ui (VSCodeLayoutsHeaderBar* self)
{
#line 27 "../src/Layouts/HeaderBar.vala"
	g_return_if_fail (self != NULL);
#line 121 "HeaderBar.c"
}

VSCodeWindow*
vs_code_layouts_header_bar_get_window (VSCodeLayoutsHeaderBar* self)
{
	VSCodeWindow* result;
	VSCodeWindow* _tmp0_;
#line 3 "../src/Layouts/HeaderBar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 3 "../src/Layouts/HeaderBar.vala"
	_tmp0_ = self->priv->_window;
#line 3 "../src/Layouts/HeaderBar.vala"
	result = _tmp0_;
#line 3 "../src/Layouts/HeaderBar.vala"
	return result;
#line 137 "HeaderBar.c"
}

static void
vs_code_layouts_header_bar_set_window (VSCodeLayoutsHeaderBar* self,
                                       VSCodeWindow* value)
{
	VSCodeWindow* old_value;
#line 3 "../src/Layouts/HeaderBar.vala"
	g_return_if_fail (self != NULL);
#line 3 "../src/Layouts/HeaderBar.vala"
	old_value = vs_code_layouts_header_bar_get_window (self);
#line 3 "../src/Layouts/HeaderBar.vala"
	if (old_value != value) {
#line 3 "../src/Layouts/HeaderBar.vala"
		self->priv->_window = value;
#line 3 "../src/Layouts/HeaderBar.vala"
		g_object_notify_by_pspec ((GObject *) self, vs_code_layouts_header_bar_properties[VS_CODE_LAYOUTS_HEADER_BAR_WINDOW_PROPERTY]);
#line 155 "HeaderBar.c"
	}
}

gboolean
vs_code_layouts_header_bar_get_logged_out (VSCodeLayoutsHeaderBar* self)
{
	gboolean result;
#line 12 "../src/Layouts/HeaderBar.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 12 "../src/Layouts/HeaderBar.vala"
	result = self->priv->_logged_out;
#line 12 "../src/Layouts/HeaderBar.vala"
	return result;
#line 169 "HeaderBar.c"
}

void
vs_code_layouts_header_bar_set_logged_out (VSCodeLayoutsHeaderBar* self,
                                           gboolean value)
{
	gboolean old_value;
#line 12 "../src/Layouts/HeaderBar.vala"
	g_return_if_fail (self != NULL);
#line 12 "../src/Layouts/HeaderBar.vala"
	old_value = vs_code_layouts_header_bar_get_logged_out (self);
#line 12 "../src/Layouts/HeaderBar.vala"
	if (old_value != value) {
#line 12 "../src/Layouts/HeaderBar.vala"
		self->priv->_logged_out = value;
#line 12 "../src/Layouts/HeaderBar.vala"
		g_object_notify_by_pspec ((GObject *) self, vs_code_layouts_header_bar_properties[VS_CODE_LAYOUTS_HEADER_BAR_LOGGED_OUT_PROPERTY]);
#line 187 "HeaderBar.c"
	}
}

static void
vs_code_layouts_header_bar_class_init (VSCodeLayoutsHeaderBarClass * klass,
                                       gpointer klass_data)
{
#line 2 "../src/Layouts/HeaderBar.vala"
	vs_code_layouts_header_bar_parent_class = g_type_class_peek_parent (klass);
#line 2 "../src/Layouts/HeaderBar.vala"
	g_type_class_adjust_private_offset (klass, &VSCodeLayoutsHeaderBar_private_offset);
#line 2 "../src/Layouts/HeaderBar.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_vs_code_layouts_header_bar_get_property;
#line 2 "../src/Layouts/HeaderBar.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_vs_code_layouts_header_bar_set_property;
#line 2 "../src/Layouts/HeaderBar.vala"
	G_OBJECT_CLASS (klass)->finalize = vs_code_layouts_header_bar_finalize;
#line 2 "../src/Layouts/HeaderBar.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), VS_CODE_LAYOUTS_HEADER_BAR_WINDOW_PROPERTY, vs_code_layouts_header_bar_properties[VS_CODE_LAYOUTS_HEADER_BAR_WINDOW_PROPERTY] = g_param_spec_object ("window", "window", "window", VS_CODE_TYPE_WINDOW, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 2 "../src/Layouts/HeaderBar.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), VS_CODE_LAYOUTS_HEADER_BAR_LOGGED_OUT_PROPERTY, vs_code_layouts_header_bar_properties[VS_CODE_LAYOUTS_HEADER_BAR_LOGGED_OUT_PROPERTY] = g_param_spec_boolean ("logged-out", "logged-out", "logged-out", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 209 "HeaderBar.c"
}

static void
vs_code_layouts_header_bar_instance_init (VSCodeLayoutsHeaderBar * self,
                                          gpointer klass)
{
#line 2 "../src/Layouts/HeaderBar.vala"
	self->priv = vs_code_layouts_header_bar_get_instance_private (self);
#line 218 "HeaderBar.c"
}

static void
vs_code_layouts_header_bar_finalize (GObject * obj)
{
	VSCodeLayoutsHeaderBar * self;
#line 2 "../src/Layouts/HeaderBar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBar);
#line 2 "../src/Layouts/HeaderBar.vala"
	G_OBJECT_CLASS (vs_code_layouts_header_bar_parent_class)->finalize (obj);
#line 229 "HeaderBar.c"
}

static GType
vs_code_layouts_header_bar_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (VSCodeLayoutsHeaderBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vs_code_layouts_header_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (VSCodeLayoutsHeaderBar), 0, (GInstanceInitFunc) vs_code_layouts_header_bar_instance_init, NULL };
	GType vs_code_layouts_header_bar_type_id;
	vs_code_layouts_header_bar_type_id = g_type_register_static (gtk_header_bar_get_type (), "VSCodeLayoutsHeaderBar", &g_define_type_info, 0);
	VSCodeLayoutsHeaderBar_private_offset = g_type_add_instance_private (vs_code_layouts_header_bar_type_id, sizeof (VSCodeLayoutsHeaderBarPrivate));
	return vs_code_layouts_header_bar_type_id;
}

GType
vs_code_layouts_header_bar_get_type (void)
{
	static volatile gsize vs_code_layouts_header_bar_type_id__volatile = 0;
	if (g_once_init_enter (&vs_code_layouts_header_bar_type_id__volatile)) {
		GType vs_code_layouts_header_bar_type_id;
		vs_code_layouts_header_bar_type_id = vs_code_layouts_header_bar_get_type_once ();
		g_once_init_leave (&vs_code_layouts_header_bar_type_id__volatile, vs_code_layouts_header_bar_type_id);
	}
	return vs_code_layouts_header_bar_type_id__volatile;
}

static void
_vala_vs_code_layouts_header_bar_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec)
{
	VSCodeLayoutsHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBar);
#line 2 "../src/Layouts/HeaderBar.vala"
	switch (property_id) {
#line 2 "../src/Layouts/HeaderBar.vala"
		case VS_CODE_LAYOUTS_HEADER_BAR_WINDOW_PROPERTY:
#line 2 "../src/Layouts/HeaderBar.vala"
		g_value_set_object (value, vs_code_layouts_header_bar_get_window (self));
#line 2 "../src/Layouts/HeaderBar.vala"
		break;
#line 2 "../src/Layouts/HeaderBar.vala"
		case VS_CODE_LAYOUTS_HEADER_BAR_LOGGED_OUT_PROPERTY:
#line 2 "../src/Layouts/HeaderBar.vala"
		g_value_set_boolean (value, vs_code_layouts_header_bar_get_logged_out (self));
#line 2 "../src/Layouts/HeaderBar.vala"
		break;
#line 276 "HeaderBar.c"
		default:
#line 2 "../src/Layouts/HeaderBar.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Layouts/HeaderBar.vala"
		break;
#line 282 "HeaderBar.c"
	}
}

static void
_vala_vs_code_layouts_header_bar_set_property (GObject * object,
                                               guint property_id,
                                               const GValue * value,
                                               GParamSpec * pspec)
{
	VSCodeLayoutsHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VS_CODE_LAYOUTS_TYPE_HEADER_BAR, VSCodeLayoutsHeaderBar);
#line 2 "../src/Layouts/HeaderBar.vala"
	switch (property_id) {
#line 2 "../src/Layouts/HeaderBar.vala"
		case VS_CODE_LAYOUTS_HEADER_BAR_WINDOW_PROPERTY:
#line 2 "../src/Layouts/HeaderBar.vala"
		vs_code_layouts_header_bar_set_window (self, g_value_get_object (value));
#line 2 "../src/Layouts/HeaderBar.vala"
		break;
#line 2 "../src/Layouts/HeaderBar.vala"
		case VS_CODE_LAYOUTS_HEADER_BAR_LOGGED_OUT_PROPERTY:
#line 2 "../src/Layouts/HeaderBar.vala"
		vs_code_layouts_header_bar_set_logged_out (self, g_value_get_boolean (value));
#line 2 "../src/Layouts/HeaderBar.vala"
		break;
#line 308 "HeaderBar.c"
		default:
#line 2 "../src/Layouts/HeaderBar.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Layouts/HeaderBar.vala"
		break;
#line 314 "HeaderBar.c"
	}
}

