/* Welcome.c generated by valac 0.48.25, the Vala compiler
 * generated from Welcome.vala, do not modify */

#include <granite.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <glib/gi18n-lib.h>

#define VS_CODE_LAYOUTS_TYPE_WELCOME (vs_code_layouts_welcome_get_type ())
#define VS_CODE_LAYOUTS_WELCOME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_LAYOUTS_TYPE_WELCOME, VSCodeLayoutsWelcome))
#define VS_CODE_LAYOUTS_WELCOME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_LAYOUTS_TYPE_WELCOME, VSCodeLayoutsWelcomeClass))
#define VS_CODE_LAYOUTS_IS_WELCOME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_LAYOUTS_TYPE_WELCOME))
#define VS_CODE_LAYOUTS_IS_WELCOME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_LAYOUTS_TYPE_WELCOME))
#define VS_CODE_LAYOUTS_WELCOME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_LAYOUTS_TYPE_WELCOME, VSCodeLayoutsWelcomeClass))

typedef struct _VSCodeLayoutsWelcome VSCodeLayoutsWelcome;
typedef struct _VSCodeLayoutsWelcomeClass VSCodeLayoutsWelcomeClass;
typedef struct _VSCodeLayoutsWelcomePrivate VSCodeLayoutsWelcomePrivate;

#define VS_CODE_TYPE_WINDOW (vs_code_window_get_type ())
#define VS_CODE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VS_CODE_TYPE_WINDOW, VSCodeWindow))
#define VS_CODE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VS_CODE_TYPE_WINDOW, VSCodeWindowClass))
#define VS_CODE_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VS_CODE_TYPE_WINDOW))
#define VS_CODE_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VS_CODE_TYPE_WINDOW))
#define VS_CODE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VS_CODE_TYPE_WINDOW, VSCodeWindowClass))

typedef struct _VSCodeWindow VSCodeWindow;
typedef struct _VSCodeWindowClass VSCodeWindowClass;
enum  {
	VS_CODE_LAYOUTS_WELCOME_0_PROPERTY,
	VS_CODE_LAYOUTS_WELCOME_WINDOW_PROPERTY,
	VS_CODE_LAYOUTS_WELCOME_NUM_PROPERTIES
};
static GParamSpec* vs_code_layouts_welcome_properties[VS_CODE_LAYOUTS_WELCOME_NUM_PROPERTIES];

struct _VSCodeLayoutsWelcome {
	GraniteWidgetsWelcome parent_instance;
	VSCodeLayoutsWelcomePrivate * priv;
};

struct _VSCodeLayoutsWelcomeClass {
	GraniteWidgetsWelcomeClass parent_class;
};

struct _VSCodeLayoutsWelcomePrivate {
	VSCodeWindow* _window;
};

static gint VSCodeLayoutsWelcome_private_offset;
static gpointer vs_code_layouts_welcome_parent_class = NULL;

GType vs_code_layouts_welcome_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeLayoutsWelcome, g_object_unref)
GType vs_code_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (VSCodeWindow, g_object_unref)
VSCodeLayoutsWelcome* vs_code_layouts_welcome_new (VSCodeWindow* main_window);
VSCodeLayoutsWelcome* vs_code_layouts_welcome_construct (GType object_type,
                                                         VSCodeWindow* main_window);
VSCodeWindow* vs_code_layouts_welcome_get_window (VSCodeLayoutsWelcome* self);
static void vs_code_layouts_welcome_set_window (VSCodeLayoutsWelcome* self,
                                         VSCodeWindow* value);
static GObject * vs_code_layouts_welcome_constructor (GType type,
                                               guint n_construct_properties,
                                               GObjectConstructParam * construct_properties);
static void _vs_code_layouts_welcome___lambda4_ (VSCodeLayoutsWelcome* self,
                                          gint index);
static void __vs_code_layouts_welcome___lambda4__granite_widgets_welcome_activated (GraniteWidgetsWelcome* _sender,
                                                                             gint index,
                                                                             gpointer self);
static void vs_code_layouts_welcome_finalize (GObject * obj);
static GType vs_code_layouts_welcome_get_type_once (void);
static void _vala_vs_code_layouts_welcome_get_property (GObject * object,
                                                 guint property_id,
                                                 GValue * value,
                                                 GParamSpec * pspec);
static void _vala_vs_code_layouts_welcome_set_property (GObject * object,
                                                 guint property_id,
                                                 const GValue * value,
                                                 GParamSpec * pspec);

static inline gpointer
vs_code_layouts_welcome_get_instance_private (VSCodeLayoutsWelcome* self)
{
	return G_STRUCT_MEMBER_P (self, VSCodeLayoutsWelcome_private_offset);
}

VSCodeLayoutsWelcome*
vs_code_layouts_welcome_construct (GType object_type,
                                   VSCodeWindow* main_window)
{
	VSCodeLayoutsWelcome * self = NULL;
#line 5 "../src/Layouts/Welcome.vala"
	g_return_val_if_fail (main_window != NULL, NULL);
#line 6 "../src/Layouts/Welcome.vala"
	self = (VSCodeLayoutsWelcome*) g_object_new (object_type, "window", main_window, "title", _ ("Welcome to Sequeler"), "subtitle", _ ("Connect to Any Local or Remote Database."), NULL);
#line 5 "../src/Layouts/Welcome.vala"
	return self;
#line 100 "Welcome.c"
}

VSCodeLayoutsWelcome*
vs_code_layouts_welcome_new (VSCodeWindow* main_window)
{
#line 5 "../src/Layouts/Welcome.vala"
	return vs_code_layouts_welcome_construct (VS_CODE_LAYOUTS_TYPE_WELCOME, main_window);
#line 108 "Welcome.c"
}

VSCodeWindow*
vs_code_layouts_welcome_get_window (VSCodeLayoutsWelcome* self)
{
	VSCodeWindow* result;
	VSCodeWindow* _tmp0_;
#line 3 "../src/Layouts/Welcome.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 3 "../src/Layouts/Welcome.vala"
	_tmp0_ = self->priv->_window;
#line 3 "../src/Layouts/Welcome.vala"
	result = _tmp0_;
#line 3 "../src/Layouts/Welcome.vala"
	return result;
#line 124 "Welcome.c"
}

static void
vs_code_layouts_welcome_set_window (VSCodeLayoutsWelcome* self,
                                    VSCodeWindow* value)
{
	VSCodeWindow* old_value;
#line 3 "../src/Layouts/Welcome.vala"
	g_return_if_fail (self != NULL);
#line 3 "../src/Layouts/Welcome.vala"
	old_value = vs_code_layouts_welcome_get_window (self);
#line 3 "../src/Layouts/Welcome.vala"
	if (old_value != value) {
#line 3 "../src/Layouts/Welcome.vala"
		self->priv->_window = value;
#line 3 "../src/Layouts/Welcome.vala"
		g_object_notify_by_pspec ((GObject *) self, vs_code_layouts_welcome_properties[VS_CODE_LAYOUTS_WELCOME_WINDOW_PROPERTY]);
#line 142 "Welcome.c"
	}
}

static void
_vs_code_layouts_welcome___lambda4_ (VSCodeLayoutsWelcome* self,
                                     gint index)
{
#line 23 "../src/Layouts/Welcome.vala"
	switch (index) {
#line 23 "../src/Layouts/Welcome.vala"
		case 0:
#line 154 "Welcome.c"
		{
#line 26 "../src/Layouts/Welcome.vala"
			break;
#line 158 "Welcome.c"
		}
#line 23 "../src/Layouts/Welcome.vala"
		case 1:
#line 162 "Welcome.c"
		{
#line 29 "../src/Layouts/Welcome.vala"
			break;
#line 166 "Welcome.c"
		}
#line 23 "../src/Layouts/Welcome.vala"
		case 2:
#line 170 "Welcome.c"
		{
#line 32 "../src/Layouts/Welcome.vala"
			break;
#line 174 "Welcome.c"
		}
		default:
#line 23 "../src/Layouts/Welcome.vala"
		break;
#line 179 "Welcome.c"
	}
}

static void
__vs_code_layouts_welcome___lambda4__granite_widgets_welcome_activated (GraniteWidgetsWelcome* _sender,
                                                                        gint index,
                                                                        gpointer self)
{
#line 22 "../src/Layouts/Welcome.vala"
	_vs_code_layouts_welcome___lambda4_ ((VSCodeLayoutsWelcome*) self, index);
#line 190 "Welcome.c"
}

static GObject *
vs_code_layouts_welcome_constructor (GType type,
                                     guint n_construct_properties,
                                     GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	VSCodeLayoutsWelcome * self;
#line 13 "../src/Layouts/Welcome.vala"
	parent_class = G_OBJECT_CLASS (vs_code_layouts_welcome_parent_class);
#line 13 "../src/Layouts/Welcome.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 13 "../src/Layouts/Welcome.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VS_CODE_LAYOUTS_TYPE_WELCOME, VSCodeLayoutsWelcome);
#line 14 "../src/Layouts/Welcome.vala"
	gtk_widget_set_valign ((GtkWidget*) self, GTK_ALIGN_FILL);
#line 15 "../src/Layouts/Welcome.vala"
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_FILL);
#line 16 "../src/Layouts/Welcome.vala"
	gtk_widget_set_vexpand ((GtkWidget*) self, TRUE);
#line 18 "../src/Layouts/Welcome.vala"
	granite_widgets_welcome_append ((GraniteWidgetsWelcome*) self, "bookmark-new", _ ("Add a New Database"), _ ("Connect to a Database and Save It in Your Library"));
#line 19 "../src/Layouts/Welcome.vala"
	granite_widgets_welcome_append ((GraniteWidgetsWelcome*) self, "window-new", _ ("New Window"), _ ("Open a New Sequeler Window"));
#line 20 "../src/Layouts/Welcome.vala"
	granite_widgets_welcome_append ((GraniteWidgetsWelcome*) self, "folder-download", _ ("Import Connections"), _ ("Import Previously Exported Sequeler Connections"));
#line 22 "../src/Layouts/Welcome.vala"
	g_signal_connect_object ((GraniteWidgetsWelcome*) self, "activated", (GCallback) __vs_code_layouts_welcome___lambda4__granite_widgets_welcome_activated, self, 0);
#line 13 "../src/Layouts/Welcome.vala"
	return obj;
#line 223 "Welcome.c"
}

static void
vs_code_layouts_welcome_class_init (VSCodeLayoutsWelcomeClass * klass,
                                    gpointer klass_data)
{
#line 2 "../src/Layouts/Welcome.vala"
	vs_code_layouts_welcome_parent_class = g_type_class_peek_parent (klass);
#line 2 "../src/Layouts/Welcome.vala"
	g_type_class_adjust_private_offset (klass, &VSCodeLayoutsWelcome_private_offset);
#line 2 "../src/Layouts/Welcome.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_vs_code_layouts_welcome_get_property;
#line 2 "../src/Layouts/Welcome.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_vs_code_layouts_welcome_set_property;
#line 2 "../src/Layouts/Welcome.vala"
	G_OBJECT_CLASS (klass)->constructor = vs_code_layouts_welcome_constructor;
#line 2 "../src/Layouts/Welcome.vala"
	G_OBJECT_CLASS (klass)->finalize = vs_code_layouts_welcome_finalize;
#line 2 "../src/Layouts/Welcome.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), VS_CODE_LAYOUTS_WELCOME_WINDOW_PROPERTY, vs_code_layouts_welcome_properties[VS_CODE_LAYOUTS_WELCOME_WINDOW_PROPERTY] = g_param_spec_object ("window", "window", "window", VS_CODE_TYPE_WINDOW, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 244 "Welcome.c"
}

static void
vs_code_layouts_welcome_instance_init (VSCodeLayoutsWelcome * self,
                                       gpointer klass)
{
#line 2 "../src/Layouts/Welcome.vala"
	self->priv = vs_code_layouts_welcome_get_instance_private (self);
#line 253 "Welcome.c"
}

static void
vs_code_layouts_welcome_finalize (GObject * obj)
{
	VSCodeLayoutsWelcome * self;
#line 2 "../src/Layouts/Welcome.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VS_CODE_LAYOUTS_TYPE_WELCOME, VSCodeLayoutsWelcome);
#line 2 "../src/Layouts/Welcome.vala"
	G_OBJECT_CLASS (vs_code_layouts_welcome_parent_class)->finalize (obj);
#line 264 "Welcome.c"
}

static GType
vs_code_layouts_welcome_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (VSCodeLayoutsWelcomeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vs_code_layouts_welcome_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (VSCodeLayoutsWelcome), 0, (GInstanceInitFunc) vs_code_layouts_welcome_instance_init, NULL };
	GType vs_code_layouts_welcome_type_id;
	vs_code_layouts_welcome_type_id = g_type_register_static (GRANITE_WIDGETS_TYPE_WELCOME, "VSCodeLayoutsWelcome", &g_define_type_info, 0);
	VSCodeLayoutsWelcome_private_offset = g_type_add_instance_private (vs_code_layouts_welcome_type_id, sizeof (VSCodeLayoutsWelcomePrivate));
	return vs_code_layouts_welcome_type_id;
}

GType
vs_code_layouts_welcome_get_type (void)
{
	static volatile gsize vs_code_layouts_welcome_type_id__volatile = 0;
	if (g_once_init_enter (&vs_code_layouts_welcome_type_id__volatile)) {
		GType vs_code_layouts_welcome_type_id;
		vs_code_layouts_welcome_type_id = vs_code_layouts_welcome_get_type_once ();
		g_once_init_leave (&vs_code_layouts_welcome_type_id__volatile, vs_code_layouts_welcome_type_id);
	}
	return vs_code_layouts_welcome_type_id__volatile;
}

static void
_vala_vs_code_layouts_welcome_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec)
{
	VSCodeLayoutsWelcome * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VS_CODE_LAYOUTS_TYPE_WELCOME, VSCodeLayoutsWelcome);
#line 2 "../src/Layouts/Welcome.vala"
	switch (property_id) {
#line 2 "../src/Layouts/Welcome.vala"
		case VS_CODE_LAYOUTS_WELCOME_WINDOW_PROPERTY:
#line 2 "../src/Layouts/Welcome.vala"
		g_value_set_object (value, vs_code_layouts_welcome_get_window (self));
#line 2 "../src/Layouts/Welcome.vala"
		break;
#line 305 "Welcome.c"
		default:
#line 2 "../src/Layouts/Welcome.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Layouts/Welcome.vala"
		break;
#line 311 "Welcome.c"
	}
}

static void
_vala_vs_code_layouts_welcome_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec)
{
	VSCodeLayoutsWelcome * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VS_CODE_LAYOUTS_TYPE_WELCOME, VSCodeLayoutsWelcome);
#line 2 "../src/Layouts/Welcome.vala"
	switch (property_id) {
#line 2 "../src/Layouts/Welcome.vala"
		case VS_CODE_LAYOUTS_WELCOME_WINDOW_PROPERTY:
#line 2 "../src/Layouts/Welcome.vala"
		vs_code_layouts_welcome_set_window (self, g_value_get_object (value));
#line 2 "../src/Layouts/Welcome.vala"
		break;
#line 331 "Welcome.c"
		default:
#line 2 "../src/Layouts/Welcome.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Layouts/Welcome.vala"
		break;
#line 337 "Welcome.c"
	}
}

